name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tets
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      HOST: '0.0.0.0'
      DATABASE_URL: 'postgresql://example'
      PORT: 3333
      JWT_SECRET: 'SECRET_PASSWORD'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run test
